[package]
name         = "cypher-tck"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
authors      = { workspace = true }
repository   = { workspace = true }
description  = "openCypher TCK harness. Spec 0001 §17.5."

[dependencies]
cypher-db = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
