// @generated by `cargo xtask codegen`. DO NOT EDIT.
// Source: crates/cypher-ast/cypher.ungrammar (spec 0001 §5.2).
//
// Typed AST wrappers are zero-cost views over `cypher_syntax::SyntaxNode`
// (spec §5.1). Each wrapper has a `cast` that succeeds iff the underlying
// node's `SyntaxKind` matches, plus `Option`-returning accessors per
// child (spec §5.3).
//
// SKIPPED (no wrapper emitted — productions listed below):
//   - Statement: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - SingleQuery: no `SyntaxKind::SINGLE_QUERY` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - Union: no `SyntaxKind::UNION` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - Clause: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - ReturnItems: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - Skip: no `SyntaxKind::SKIP` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - Limit: no `SyntaxKind::LIMIT` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - Expr: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - NameDef: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - QualifiedName: no `SyntaxKind::QUALIFIED_NAME` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - YieldClause: no `SyntaxKind::YIELD_CLAUSE` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - SetItem: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - RemoveItem: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - SortItem: no `SyntaxKind::SORT_ITEM` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - NameRef: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - PropertyAssign: no `SyntaxKind::PROPERTY_ASSIGN` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - LabelAdd: no `SyntaxKind::LABEL_ADD` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - NodeReplace: no `SyntaxKind::NODE_REPLACE` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - NodeMerge: no `SyntaxKind::NODE_MERGE` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - PropertyAccess: no `SyntaxKind::PROPERTY_ACCESS` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - PropertyRemove: no `SyntaxKind::PROPERTY_REMOVE` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - LabelRemove: no `SyntaxKind::LABEL_REMOVE` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - PathPattern: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - ShortestPathPattern: no `SyntaxKind::SHORTEST_PATH_PATTERN` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - PathElement: no `SyntaxKind::PATH_ELEMENT` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - RelPattern: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - TypeExpr: no `SyntaxKind::TYPE_EXPR` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - RangeHops: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - IntLiteral: no `SyntaxKind::INT_LITERAL` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - Label: no `SyntaxKind::LABEL` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - RelType: no `SyntaxKind::REL_TYPE` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - PropertyKV: no `SyntaxKind::PROPERTY_K_V` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - PropertyKey: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - Literal: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - ParameterExpr: no `SyntaxKind::PARAMETER_EXPR` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - VariableRef: no `SyntaxKind::VARIABLE_REF` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - IndexAccess: no `SyntaxKind::INDEX_ACCESS` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - CountStar: no `SyntaxKind::COUNT_STAR` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - NullCheck: no `SyntaxKind::NULL_CHECK` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - ExistsPredicate: no `SyntaxKind::EXISTS_PREDICATE` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - StringPatternExpr: no `SyntaxKind::STRING_PATTERN_EXPR` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - MembershipExpr: no `SyntaxKind::MEMBERSHIP_EXPR` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - FloatLiteral: no `SyntaxKind::FLOAT_LITERAL` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - StringLiteral: no `SyntaxKind::STRING_LITERAL` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - BoolLiteral: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - NullLiteral: no `SyntaxKind::NULL_LITERAL` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - WhenArm: no `SyntaxKind::WHEN_ARM` variant in cypher-syntax::kind (see cy-nom follow-ups)
//   - BinaryOp: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - UnaryOp: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)
//   - StringPatternOp: alternation-only production (sum-type enum deferred to cy-pbx, spec §5.4)

#![forbid(unsafe_code)]
#![allow(clippy::wildcard_imports)]
#![allow(clippy::return_self_not_must_use)]
#![allow(dead_code)]

use cypher_syntax::{SyntaxElement, SyntaxKind, SyntaxNode, SyntaxToken};

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SourceFile {
    syntax: SyntaxNode,
}

impl SourceFile {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::SOURCE_FILE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UnionTail {
    syntax: SyntaxNode,
}

impl UnionTail {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::UNION_TAIL).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn union_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::UNION_KW)
    }

    pub fn all_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::ALL_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MatchClause {
    syntax: SyntaxNode,
}

impl MatchClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::MATCH_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn pattern(&self) -> impl Iterator<Item = Pattern> + '_ {
        self.syntax.children().filter_map(Pattern::cast)
    }

    pub fn where_clause(&self) -> Option<WhereClause> {
        self.syntax.children().find_map(WhereClause::cast)
    }

    pub fn optional_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::OPTIONAL_KW)
    }

    pub fn match_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::MATCH_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WithClause {
    syntax: SyntaxNode,
}

impl WithClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::WITH_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn where_clause(&self) -> Option<WhereClause> {
        self.syntax.children().find_map(WhereClause::cast)
    }

    pub fn order_by(&self) -> Option<OrderBy> {
        self.syntax.children().find_map(OrderBy::cast)
    }

    pub fn with_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::WITH_KW)
    }

    pub fn distinct_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::DISTINCT_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ReturnClause {
    syntax: SyntaxNode,
}

impl ReturnClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::RETURN_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn order_by(&self) -> Option<OrderBy> {
        self.syntax.children().find_map(OrderBy::cast)
    }

    pub fn return_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::RETURN_KW)
    }

    pub fn distinct_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::DISTINCT_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UnwindClause {
    syntax: SyntaxNode,
}

impl UnwindClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::UNWIND_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn unwind_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::UNWIND_KW)
    }

    pub fn as_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::AS_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CallClause {
    syntax: SyntaxNode,
}

impl CallClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::CALL_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn arg_list(&self) -> Option<ArgList> {
        self.syntax.children().find_map(ArgList::cast)
    }

    pub fn call_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::CALL_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CreateClause {
    syntax: SyntaxNode,
}

impl CreateClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::CREATE_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn pattern(&self) -> impl Iterator<Item = Pattern> + '_ {
        self.syntax.children().filter_map(Pattern::cast)
    }

    pub fn create_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::CREATE_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MergeClause {
    syntax: SyntaxNode,
}

impl MergeClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::MERGE_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn pattern(&self) -> Option<Pattern> {
        self.syntax.children().find_map(Pattern::cast)
    }

    pub fn merge_action(&self) -> impl Iterator<Item = MergeAction> + '_ {
        self.syntax.children().filter_map(MergeAction::cast)
    }

    pub fn merge_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::MERGE_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SetClause {
    syntax: SyntaxNode,
}

impl SetClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::SET_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn set_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::SET_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RemoveClause {
    syntax: SyntaxNode,
}

impl RemoveClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::REMOVE_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn remove_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::REMOVE_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct DeleteClause {
    syntax: SyntaxNode,
}

impl DeleteClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::DELETE_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn detach_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::DETACH_KW)
    }

    pub fn delete_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::DELETE_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Pattern {
    syntax: SyntaxNode,
}

impl Pattern {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PATTERN).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WhereClause {
    syntax: SyntaxNode,
}

impl WhereClause {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::WHERE_CLAUSE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn where_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::WHERE_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct OrderBy {
    syntax: SyntaxNode,
}

impl OrderBy {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::ORDER_BY).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn order_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::ORDER_KW)
    }

    pub fn by_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::BY_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArgList {
    syntax: SyntaxNode,
}

impl ArgList {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::ARG_LIST).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct YieldItem {
    syntax: SyntaxNode,
}

impl YieldItem {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::YIELD_ITEM).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn as_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::AS_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MergeAction {
    syntax: SyntaxNode,
}

impl MergeAction {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::MERGE_ACTION).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn set_clause(&self) -> Option<SetClause> {
        self.syntax.children().find_map(SetClause::cast)
    }

    pub fn on_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::ON_KW)
    }

    pub fn create_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::CREATE_KW)
    }

    pub fn match_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::MATCH_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ReturnItem {
    syntax: SyntaxNode,
}

impl ReturnItem {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::RETURN_ITEM).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn as_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::AS_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct LabelExpr {
    syntax: SyntaxNode,
}

impl LabelExpr {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::LABEL_EXPR).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NodePattern {
    syntax: SyntaxNode,
}

impl NodePattern {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::NODE_PATTERN).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn label_expr(&self) -> Option<LabelExpr> {
        self.syntax.children().find_map(LabelExpr::cast)
    }

    pub fn property_map(&self) -> Option<PropertyMap> {
        self.syntax.children().find_map(PropertyMap::cast)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PropertyMap {
    syntax: SyntaxNode,
}

impl PropertyMap {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PROPERTY_MAP).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RelDetail {
    syntax: SyntaxNode,
}

impl RelDetail {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::REL_DETAIL).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn property_map(&self) -> Option<PropertyMap> {
        self.syntax.children().find_map(PropertyMap::cast)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FunctionCall {
    syntax: SyntaxNode,
}

impl FunctionCall {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::FUNCTION_CALL).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn arg_list(&self) -> Option<ArgList> {
        self.syntax.children().find_map(ArgList::cast)
    }

    pub fn distinct_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::DISTINCT_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ParenExpr {
    syntax: SyntaxNode,
}

impl ParenExpr {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PAREN_EXPR).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ListLiteral {
    syntax: SyntaxNode,
}

impl ListLiteral {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::LIST_LITERAL).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MapLiteral {
    syntax: SyntaxNode,
}

impl MapLiteral {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::MAP_LITERAL).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ListComprehension {
    syntax: SyntaxNode,
}

impl ListComprehension {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::LIST_COMPREHENSION).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn where_clause(&self) -> Option<WhereClause> {
        self.syntax.children().find_map(WhereClause::cast)
    }

    pub fn in_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::IN_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PatternComprehension {
    syntax: SyntaxNode,
}

impl PatternComprehension {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PATTERN_COMPREHENSION).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn where_clause(&self) -> Option<WhereClause> {
        self.syntax.children().find_map(WhereClause::cast)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CaseExpr {
    syntax: SyntaxNode,
}

impl CaseExpr {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::CASE_EXPR).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }

    pub fn case_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::CASE_KW)
    }

    pub fn else_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::ELSE_KW)
    }

    pub fn end_token(&self) -> Option<SyntaxToken> {
        self.syntax
            .children_with_tokens()
            .filter_map(SyntaxElement::into_token)
            .find(|t| t.kind() == SyntaxKind::END_KW)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BinaryExpr {
    syntax: SyntaxNode,
}

impl BinaryExpr {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::BINARY_EXPR).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UnaryExpr {
    syntax: SyntaxNode,
}

impl UnaryExpr {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::UNARY_EXPR).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PatternPredicate {
    syntax: SyntaxNode,
}

impl PatternPredicate {
    pub fn cast(syntax: SyntaxNode) -> Option<Self> {
        (syntax.kind() == SyntaxKind::PATTERN_PREDICATE).then_some(Self { syntax })
    }

    pub fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
