//! `cypher-ast` — typed AST wrappers over the CST (spec 0001 §5).
//!
//! AST nodes are zero-cost wrappers around [`cypher_syntax::SyntaxNode`].
//! A node's methods navigate the underlying tree; no duplication, no
//! allocation. Per §5.2, the bulk of wrappers is generated from a
//! grammar description by a dev-only `xtask`; the output lives in the
//! checked-in [`generated`] module and is regenerated by
//! `cargo xtask codegen`.

#![forbid(unsafe_code)]
#![doc(html_root_url = "https://docs.rs/cypher-ast/0.0.1")]

use cypher_syntax::{SyntaxKind, SyntaxNode};

pub mod generated;
pub use generated::*;

/// Trait every typed AST wrapper conforms to. Modelled after the
/// rust-analyzer `AstNode` pattern. The `generated` module emits plain
/// `cast`/`syntax` methods directly (matching the spec §5.1 shape); this
/// trait is the portable handle hand-written or macro-based wrappers use.
pub trait AstNode: Sized {
    /// `true` iff a node with this `kind` can be cast to `Self`.
    fn can_cast(kind: SyntaxKind) -> bool;
    /// Attempt to cast a raw `SyntaxNode` to this typed wrapper.
    /// Returns `None` when the node's `SyntaxKind` doesn't match.
    fn cast(syntax: SyntaxNode) -> Option<Self>;
    /// Return the underlying `SyntaxNode`.  Zero-cost — typed
    /// wrappers are `repr(transparent)`-style views.
    fn syntax(&self) -> &SyntaxNode;
}

#[cfg(test)]
mod tests {
    use super::*;
    use cypher_syntax::parse;

    #[test]
    fn cast_source_file_from_generated() {
        let parse = parse("");
        // `SourceFile` comes from `generated::*`.
        let src = SourceFile::cast(parse.syntax()).expect("SOURCE_FILE root");
        // Trivial sanity — confirm the syntax handle round-trips.
        assert_eq!(src.syntax().kind(), SyntaxKind::SOURCE_FILE);
    }
}
