#!/usr/bin/env bash
# Regenerate per-target libFuzzer dictionaries from the shared base
# (fuzz/dicts/cypher.dict) plus per-target extras files.
#
# Usage:
#   fuzz/dicts/regen.sh
#
# Each output file under fuzz/dicts/<target>.dict is overwritten. The
# extras fragments live in fuzz/dicts/extras/<target>.dict. The shared
# base lives in fuzz/dicts/cypher.dict. Per-target dicts are embedded
# (not include-by-reference) because libFuzzer's `-dict=` flag takes a
# single flat file per target on some runners and we want the committed
# tree to match what CI passes to libFuzzer byte-for-byte.
#
# Spec §17.4 (cy-h07 acceptance: each per-target dict has > 100 entries).

set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
base=$here/cypher.dict

if [[ ! -f $base ]]; then
    echo "regen.sh: missing shared base $base" >&2
    exit 1
fi

targets=(
    fuzz_lexer
    fuzz_parser
    fuzz_formatter
    fuzz_sema
    fuzz_plan
    fmt_parse_roundtrip
)

for t in "${targets[@]}"; do
    out=$here/$t.dict
    extras=$here/extras/$t.dict
    {
        printf '# Auto-generated by fuzz/dicts/regen.sh — DO NOT EDIT BY HAND.\n'
        printf '# Source: fuzz/dicts/cypher.dict + fuzz/dicts/extras/%s.dict\n' "$t"
        printf '# Edit the sources and re-run regen.sh.\n'
        printf '\n'
        printf '# ===== Shared base (fuzz/dicts/cypher.dict) =====\n'
        cat "$base"
        if [[ -f $extras ]]; then
            printf '\n# ===== Target-specific extras =====\n'
            cat "$extras"
        fi
    } >"$out"
    # Count non-blank non-comment entries.
    n=$(grep -cE '^[[:space:]]*[^#[:space:]]' "$out" || true)
    echo "regenerated $out ($n entries)"
done
