//! `OpenGQL` upstream sample corpus — bead cy-qsze.
//!
//! Loads every `.gql` file under `tck/opengql-samples/`, runs each
//! through `cyrs_db::Database` in `DialectMode::GqlAligned`, and
//! writes a rolling parser-acceptance snapshot to
//! `tck/opengql-samples/baseline.md`.
//!
//! **This test never fails.**  Like the openCypher full-corpus harness
//! (`tests/full.rs`) and the GQL ISO bootstrap (`tests/gql_iso.rs`),
//! it is a measurement, not a gate.
//!
//! Run with:
//!
//! ```sh
//! cargo test -p cyrs-tck --features opengql-samples --test opengql_samples
//! ```
//!
//! See `tck/opengql-samples/README.md` for scope and
//! `tck/opengql-samples/VENDORED.md` for upstream pin / refresh
//! procedure.

#![cfg(feature = "opengql-samples")]
#![allow(clippy::uninlined_format_args)]

use std::path::{Path, PathBuf};

use cyrs_db::{DialectMode, workspace::Database};

struct SampleCase {
    rel: PathBuf,
    query: String,
}

fn walk_samples(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(root) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_file() && path.extension().and_then(|e| e.to_str()) == Some("gql") {
            out.push(path);
        }
    }
    out.sort();
    out
}

fn load_case(path: &Path, root: &Path) -> Option<SampleCase> {
    let query = std::fs::read_to_string(path).ok()?;
    let rel = path.strip_prefix(root).unwrap_or(path).to_path_buf();
    Some(SampleCase { rel, query })
}

fn parse_ok(query: &str) -> bool {
    let mut db = Database::new();
    let id = db.open_file(
        Path::new("opengql-sample.gql"),
        query.to_owned(),
        DialectMode::GqlAligned,
    );
    let Ok(out) = db.parse_cst(id) else {
        return false;
    };
    out.parse().errors().is_empty()
}

#[test]
fn opengql_samples_baseline() {
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let root = Path::new(&manifest_dir).join("tck").join("opengql-samples");
    assert!(
        root.is_dir(),
        "OpenGQL sample corpus missing: {}",
        root.display(),
    );

    let files = walk_samples(&root);
    let cases: Vec<SampleCase> = files.iter().filter_map(|p| load_case(p, &root)).collect();

    let mut results: Vec<(PathBuf, bool)> = Vec::with_capacity(cases.len());
    for case in &cases {
        results.push((case.rel.clone(), parse_ok(&case.query)));
    }

    let total = results.len();
    let accepted = results.iter().filter(|(_, ok)| *ok).count();

    let baseline_path = root.join("baseline.md");
    let body = render_baseline(&results, total, accepted);
    std::fs::write(&baseline_path, body)
        .unwrap_or_else(|e| panic!("write {}: {e}", baseline_path.display()));

    println!(
        "OpenGQL samples: parser accepts {}/{} files ({:.1} %) → {}",
        accepted,
        total,
        pct(accepted, total),
        baseline_path.display(),
    );
}

#[allow(clippy::cast_precision_loss)]
fn pct(num: usize, denom: usize) -> f64 {
    if denom == 0 {
        0.0
    } else {
        (num as f64 / denom as f64) * 100.0
    }
}

fn render_baseline(results: &[(PathBuf, bool)], total: usize, accepted: usize) -> String {
    use std::fmt::Write;

    let mut out = String::new();
    out.push_str("# OpenGQL Samples — Parser-Acceptance Baseline\n\n");
    out.push_str(
        "*Auto-generated by `cargo test -p cyrs-tck --features opengql-samples \
         --test opengql_samples`.  Do not hand-edit.*\n\n",
    );
    out.push_str(
        "This file records the rolling parser-acceptance rate of the\n\
         `cyrs-db` front-end (in `DialectMode::GqlAligned`) against\n\
         the vendored OpenGQL upstream sample corpus under\n\
         `crates/cyrs-tck/tck/opengql-samples/`.  See that directory's\n\
         `VENDORED.md` for the pinned upstream commit and\n\
         `README.md` for scope.\n\n",
    );
    let _ = writeln!(
        out,
        "## Summary\n\n- Accepted: **{}/{}** ({:.1} %)\n",
        accepted,
        total,
        pct(accepted, total),
    );
    out.push_str("\n## Per-file results\n\n");
    out.push_str("| File | Parser accepts? |\n");
    out.push_str("| ---- | --------------- |\n");
    for (rel, ok) in results {
        let mark = if *ok { "yes" } else { "no" };
        let _ = writeln!(out, "| `{}` | {} |", rel.display(), mark);
    }
    out
}
