[package]
name         = "cypher-db"
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
license      = { workspace = true }
authors      = { workspace = true }
repository   = { workspace = true }
homepage     = { workspace = true }
readme       = "README.md"
categories   = { workspace = true }
keywords     = { workspace = true }
description  = "Salsa-backed incremental analysis database for Cypher / GQL (spec 0001 §11)."

[dependencies]
cypher-syntax = { workspace = true }
cypher-ast    = { workspace = true }
cypher-hir    = { workspace = true }
cypher-sema   = { workspace = true }
cypher-schema = { workspace = true }
cypher-diag   = { workspace = true }
cypher-plan   = { workspace = true }
cypher-fmt    = { workspace = true }
smol_str      = { workspace = true }
indexmap      = { workspace = true }
tracing       = { workspace = true }
salsa         = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
