/* cypher.h — stable C ABI for the Cyrs Cypher / GQL frontend.
 *
 * Generated by `cargo xtask cbindgen`.  Do not edit by hand; regenerate
 * the file by running the xtask target.  See
 * `crates/cypher-ffi/README.md` for the memory-ownership contract
 * (spec 0004 §5.2) and the ABI stability guarantee (spec 0004 §9.2).
 */

#ifndef CYPHER_FFI_H
#define CYPHER_FFI_H

/* Generated by cbindgen; regenerate via `cargo xtask cbindgen`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Wire protocol version exported by [`cypher_proto_version`].  Mirrors the
 * agent / wasm pin (spec 0001 §15, spec 0004 §4.3, §9.2).
 */
#define PROTO_VERSION 1

/**
 * Opaque list of completion items returned by [`cypher_complete`].
 */
typedef struct CypherCompletionList CypherCompletionList;

/**
 * Opaque database handle exposed to C consumers.  Wraps one
 * [`cypher_db::Database`] plus a single `FileId` interned on first use;
 * mirrors `cypher-wasm`'s per-dialect file-registry but simplified to
 * one file (the FFI surface is one-shot per call — callers that want
 * multi-file incremental analysis should use the agent JSON API).
 *
 * # Invariants
 *
 * The struct is constructed only via [`cypher_database_new`] and torn
 * down only via [`cypher_database_free`].  A non-null `CypherDatabase`
 * pointer handed to the FFI is always a valid Rust-allocated boxed
 * value; aliasing rules forbid the caller from using the pointer
 * concurrently from multiple threads (no interior mutex here).
 */
typedef struct CypherDatabase CypherDatabase;

/**
 * Opaque list of diagnostics returned by [`cypher_check`].  Accessors
 * (`cypher_diagnostic_*`) return borrowed pointers whose lifetime is
 * tied to this list; they are freed when the list is passed to
 * [`cypher_diagnostic_list_free`].
 */
typedef struct CypherDiagnosticList CypherDiagnosticList;

/**
 * Opaque hover result returned by [`cypher_hover`].
 */
typedef struct CypherHoverResult CypherHoverResult;

/**
 * Opaque result of a [`cypher_parse`] call.  Surfaces the CST round-trip
 * as a borrowed string + the raw parser error count; use
 * [`cypher_check`] for the full diagnostic list.
 */
typedef struct CypherParseResult CypherParseResult;

/**
 * Opaque rewrite result returned by [`cypher_rewrite`].  Surfaces the
 * final rewritten text and the number of edits applied.
 */
typedef struct CypherRewriteResult CypherRewriteResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new database.  Returns an owned pointer the caller must free
 * with [`cypher_database_free`].  Returns `NULL` on panic (see
 * [`cypher_last_error`]).
 *
 * # Safety
 *
 * Calling this function has no preconditions; the returned pointer is
 * either null or a unique owned handle.
 */
CypherDatabase *cypher_database_new(void);

/**
 * Free a database previously returned by [`cypher_database_new`].
 * Passing `NULL` is a no-op.
 *
 * # Safety
 *
 * `handle` must either be null or a pointer previously returned by
 * [`cypher_database_new`] and not already freed.  After this call the
 * caller must not use `handle` for anything.
 */
void cypher_database_free(CypherDatabase *handle);

/**
 * Run the full analysis pipeline (parse + sema) and return every
 * diagnostic the db produces.  Returns `NULL` on failure (unreadable
 * source / panic); inspect [`cypher_last_error`] for details.  A
 * non-null empty list indicates "no diagnostics, source is clean".
 *
 * # Safety
 *
 * - `handle` must be a valid pointer returned by
 *   [`cypher_database_new`] (not freed).
 * - `source` must point to `source_len` UTF-8 bytes that remain valid
 *   for the duration of the call.  A null `source` with non-zero
 *   `source_len` is rejected.
 */
CypherDiagnosticList *cypher_check(CypherDatabase *handle,
                                   const char *source,
                                   uintptr_t source_len);

/**
 * Free a diagnostic list.  Passing `NULL` is a no-op.
 *
 * # Safety
 *
 * `list` must either be null or a pointer previously returned by
 * [`cypher_check`] and not already freed.
 */
void cypher_diagnostic_list_free(CypherDiagnosticList *list);

/**
 * Number of diagnostics in the list.  Returns 0 on NULL input.
 *
 * # Safety
 *
 * `list`, if non-null, must be a valid pointer previously returned by
 * [`cypher_check`] and not yet freed.
 */
uintptr_t cypher_diagnostic_list_len(const CypherDiagnosticList *list);

/**
 * Borrow the `code` of a diagnostic (e.g. `"E0001"`).  Returns `NULL` for
 * out-of-range `index` or a null list.  The returned pointer is borrowed
 * from the list and must not be freed.
 *
 * # Safety
 *
 * See [`cypher_diagnostic_list_len`].
 */
const char *cypher_diagnostic_code(const CypherDiagnosticList *list, uintptr_t index);

/**
 * Borrow the `severity` of a diagnostic as a lower-case string:
 * `"error" | "warning" | "note" | "help"`.  Returns `NULL` for
 * out-of-range input.
 *
 * # Safety
 *
 * See [`cypher_diagnostic_code`].
 */
const char *cypher_diagnostic_severity(const CypherDiagnosticList *list, uintptr_t index);

/**
 * Borrow the `message` of a diagnostic.  NUL bytes inside the source
 * message are replaced with `'?'` so the returned string is always
 * C-valid.
 *
 * # Safety
 *
 * See [`cypher_diagnostic_code`].
 */
const char *cypher_diagnostic_message(const CypherDiagnosticList *list, uintptr_t index);

/**
 * 0-based line (UTF-8) of the diagnostic's primary span start.  Returns
 * `u32::MAX` on out-of-range input.
 *
 * # Safety
 *
 * See [`cypher_diagnostic_code`].
 */
uint32_t cypher_diagnostic_start_line(const CypherDiagnosticList *list, uintptr_t index);

/**
 * 0-based UTF-8 column of the diagnostic's primary span start.
 *
 * # Safety
 *
 * See [`cypher_diagnostic_code`].
 */
uint32_t cypher_diagnostic_start_col(const CypherDiagnosticList *list, uintptr_t index);

/**
 * 0-based line of the diagnostic's primary span end.
 *
 * # Safety
 *
 * See [`cypher_diagnostic_code`].
 */
uint32_t cypher_diagnostic_end_line(const CypherDiagnosticList *list, uintptr_t index);

/**
 * 0-based UTF-8 column of the diagnostic's primary span end.
 *
 * # Safety
 *
 * See [`cypher_diagnostic_code`].
 */
uint32_t cypher_diagnostic_end_col(const CypherDiagnosticList *list, uintptr_t index);

/**
 * Parse the source into a lossless CST.  Returns an owned result the
 * caller must free with [`cypher_parse_result_free`].  Returns `NULL` on
 * invalid input / panic.
 *
 * # Safety
 *
 * See [`cypher_check`].
 */
CypherParseResult *cypher_parse(CypherDatabase *handle, const char *source, uintptr_t source_len);

/**
 * Borrow the CST round-trip string.  Returns the empty string on
 * `NULL` input.  Pointer is owned by the result; do not free it.
 *
 * # Safety
 *
 * `res`, if non-null, must be a live [`CypherParseResult`] pointer.
 */
const char *cypher_parse_result_cst(const CypherParseResult *res);

/**
 * Raw parser error count (pre-sema).  Prefer [`cypher_check`] for
 * structured diagnostics.  Returns `usize::MAX` on `NULL`.
 *
 * # Safety
 *
 * See [`cypher_parse_result_cst`].
 */
uintptr_t cypher_parse_result_error_count(const CypherParseResult *res);

/**
 * Free a parse result.  Null is a no-op.
 *
 * # Safety
 *
 * `res` must be null or a pointer previously returned by
 * [`cypher_parse`] and not yet freed.
 */
void cypher_parse_result_free(CypherParseResult *res);

/**
 * Format the source with default options.  Returns a Rust-allocated
 * NUL-terminated string the caller must free with [`cypher_string_free`].
 * Formatter errors produce the input unchanged (mirrors the agent's
 * "format is infallible" contract, spec §15).  Returns `NULL` on
 * invalid UTF-8 input or panic.
 *
 * # Safety
 *
 * See [`cypher_check`].
 */
char *cypher_format(const char *source, uintptr_t source_len);

/**
 * Free a NUL-terminated string previously returned by [`cypher_format`]
 * or [`cypher_plan_text`].  Null is a no-op.
 *
 * # Safety
 *
 * `s` must be null or a pointer previously returned by one of the
 * paired exports above and not yet freed.  Passing a pointer from a
 * different allocator is undefined behaviour.
 */
void cypher_string_free(char *s);

/**
 * Hover at byte offset `offset`.  Returns an owned pointer the caller
 * must free with [`cypher_hover_result_free`].  Returns `NULL` on bad
 * input / panic.
 *
 * # Safety
 *
 * See [`cypher_check`].
 */
CypherHoverResult *cypher_hover(CypherDatabase *handle,
                                const char *source,
                                uintptr_t source_len,
                                uint32_t offset);

/**
 * Borrowed pointer to the hover markdown.  Empty string means "no
 * content".
 *
 * # Safety
 *
 * `res`, if non-null, must be a live [`CypherHoverResult`] pointer.
 */
const char *cypher_hover_markdown(const CypherHoverResult *res);

/**
 * Hover byte-range start offset.
 *
 * # Safety
 *
 * See [`cypher_hover_markdown`].
 */
uint32_t cypher_hover_range_start(const CypherHoverResult *res);

/**
 * Hover byte-range end offset.
 *
 * # Safety
 *
 * See [`cypher_hover_markdown`].
 */
uint32_t cypher_hover_range_end(const CypherHoverResult *res);

/**
 * Free a hover result.  Null is a no-op.
 *
 * # Safety
 *
 * `res` must be null or a pointer previously returned by
 * [`cypher_hover`] and not yet freed.
 */
void cypher_hover_result_free(CypherHoverResult *res);

/**
 * Completion items at byte offset `offset`.  Returns an owned pointer
 * the caller must free with [`cypher_completion_list_free`].
 *
 * # Safety
 *
 * See [`cypher_check`].
 */
CypherCompletionList *cypher_complete(CypherDatabase *handle,
                                      const char *source,
                                      uintptr_t source_len,
                                      uint32_t offset);

/**
 * Number of completion items.  Returns 0 on NULL input.
 *
 * # Safety
 *
 * `list`, if non-null, must be a live [`CypherCompletionList`].
 */
uintptr_t cypher_completion_list_len(const CypherCompletionList *list);

/**
 * Borrow the label of a completion item.  Returns `NULL` on out-of-range.
 *
 * # Safety
 *
 * See [`cypher_completion_list_len`].
 */
const char *cypher_completion_label(const CypherCompletionList *list, uintptr_t index);

/**
 * Borrow the kind string of a completion item.  Kinds:
 * `"keyword" | "label" | "relationship_type" | "parameter" | "property" | "other"`.
 *
 * # Safety
 *
 * See [`cypher_completion_list_len`].
 */
const char *cypher_completion_kind(const CypherCompletionList *list, uintptr_t index);

/**
 * Free a completion list.  Null is a no-op.
 *
 * # Safety
 *
 * `list` must be null or a pointer previously returned by
 * [`cypher_complete`] and not yet freed.
 */
void cypher_completion_list_free(CypherCompletionList *list);

/**
 * Apply the listed `fix_ids` to `source` via the shared rewrite engine.
 * `fix_ids_json` is a JSON-encoded array of strings (e.g.
 * `["cy-fix.uppercase"]`); a NULL / empty / missing value is treated as
 * the empty list.
 *
 * # Safety
 *
 * See [`cypher_check`].  `fix_ids_json` follows the same borrow rules
 * as `source`.
 */
CypherRewriteResult *cypher_rewrite(CypherDatabase *handle,
                                    const char *source,
                                    uintptr_t source_len,
                                    const char *fix_ids_json,
                                    uintptr_t fix_ids_json_len);

/**
 * Borrowed pointer to the rewritten text.
 *
 * # Safety
 *
 * `res`, if non-null, must be a live [`CypherRewriteResult`].
 */
const char *cypher_rewrite_resulting_text(const CypherRewriteResult *res);

/**
 * Number of edits applied.
 *
 * # Safety
 *
 * See [`cypher_rewrite_resulting_text`].
 */
uintptr_t cypher_rewrite_applied_count(const CypherRewriteResult *res);

/**
 * Number of requested fix ids that did not match any diagnostic's `FixIt`.
 *
 * # Safety
 *
 * See [`cypher_rewrite_resulting_text`].
 */
uintptr_t cypher_rewrite_unknown_count(const CypherRewriteResult *res);

/**
 * Free a rewrite result.  Null is a no-op.
 *
 * # Safety
 *
 * `res` must be null or a pointer previously returned by
 * [`cypher_rewrite`] and not yet freed.
 */
void cypher_rewrite_result_free(CypherRewriteResult *res);

/**
 * Run the plan pipeline and return its debug-formatted rendering as a
 * NUL-terminated string the caller must free with [`cypher_string_free`].
 * Wire-format JSON of the plan tree lives behind the `serde` feature of
 * `cypher-plan`, which is not part of the FFI allow-list (spec 0004 §3).
 * When the neutral `plan_json` helper lands in `cypher-lang-services`
 * (cy-od5 follow-up) this will forward to it verbatim.
 *
 * # Safety
 *
 * See [`cypher_check`].
 */
char *cypher_plan_text(CypherDatabase *handle, const char *source, uintptr_t source_len);

/**
 * Return a borrowed pointer to the thread-local last-error string.  The
 * pointer is never null — when no error has occurred, it points at the
 * empty string `""`.  The pointer is valid until the next FFI call on
 * the same thread; callers must not free it.
 */
const char *cypher_last_error(void);

/**
 * Wire protocol version — see the crate-level docs.  Returns 1 today;
 * bumps are spec-governed (spec 0004 §9.2).
 */
uint32_t cypher_proto_version(void);

#if defined(CYPHER_FFI_INJECT_PANIC)
/**
 * Deliberately panic from inside an `extern "C"` body so
 * `tests/panic_safety.rs` can verify the `catch_unwind` boundary converts
 * the panic into a `cypher_last_error()` payload.  Only compiled under
 * the `inject-panic` feature — absent from release artifacts.
 */
uint32_t cypher_inject_panic(void);
#endif

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CYPHER_FFI_H */
